name: Windows x64 daemon build

on:
  workflow_dispatch:

jobs:
  win64_build:
    name: Build x64 binaries
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          choco install curl
          
      - name: Build binaries
        run: |
          cmake . -G "Unix Makefiles"
          make
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: daemon.exe
          path: daemon.exe
